
Page({

  data: {
    title: {
      text: "Color 颜色指引",
      fontWeight: '700',
      fontSize: '38rpx',
      color: '#0052d9'
    },
    mainColorBlue:[
      {
        color:'#0052d9',
        font:'white'
      },
      {
        color:'#f2f3ff',
        font:'gray'
      },
      {
        color:'#d9e1ff',
        font:'gray'
      },
      {
        color:'#b5c7ff',
        font:'gray'
      },
      {
        color:'#8eabff',
        font:'gray'
      },
      {
        color:'#618dff',
        font:'white'
      },
      {
        color:'#366ef4',
        font:'white'
      },
      {
        color:'#0052d9',
        font:'white'
      },
    ],
    mainColorRed:[
      {
        color:'#d54941',
        font:'white'
      },
      {
        color:'#fff0ed',
        font:'gray'
      },
      {
        color:'#ffd8d2',
        font:'gray'
      },
      {
        color:'#ffb9b0',
        font:'gray'
      },
      {
        color:'#ff9285',
        font:'gray'
      },
      {
        color:'#f6685d',
        font:'white'
      },
      {
        color:'#d54941',
        font:'white'
      },
      {
        color:'#ad352f',
        font:'white'
      },
    ],
    mainColorOrange:[
      {
        color:'#e37318',
        font:'white'
      },
      {
        color:'#fff1e9',
        font:'gray'
      },
      {
        color:'#ffd9c2',
        font:'gray'
      },
      {
        color:'#ffb98c',
        font:'gray'
      },
      {
        color:'#fa9550',
        font:'gray'
      },
      {
        color:'#e37318',
        font:'white'
      },
      {
        color:'#be5a00',
        font:'white'
      },
      {
        color:'#954500',
        font:'white'
      },
    ],
     mainColorGreen:[
      {
        color:'#2ba471',
        font:'white'
      },
      {
        color:'#e3f9e9',
        font:'gray'
      },
      {
        color:'#c6f3d7',
        font:'gray'
      },
      {
        color:'#92dab2',
        font:'gray'
      },
      {
        color:'#56c08d',
        font:'gray'
      },
      {
        color:'#2ba471',
        font:'white'
      },
      {
        color:'#008858',
        font:'white'
      },
      {
        color:'#006c45',
        font:'white'
      },
    ],
    mainColorGreen:[
      {
        color:'#2ba471',
        font:'white'
      },
      {
        color:'#e3f9e9',
        font:'gray'
      },
      {
        color:'#c6f3d7',
        font:'gray'
      },
      {
        color:'#92dab2',
        font:'gray'
      },
      {
        color:'#56c08d',
        font:'gray'
      },
      {
        color:'#2ba471',
        font:'white'
      },
      {
        color:'#008858',
        font:'white'
      },
      {
        color:'#006c45',
        font:'white'
      },
    ],
    kuoColorBlue:[
      {
        color:'#029cd4',
        font:'white'
      },
      {
        color:'#e8f5ff',
        font:'gray'
      },
      {
        color:'#c4e8ff',
        font:'gray'
      },
      {
        color:'#85d3ff',
        font:'gray'
      },
      {
        color:'#41b8f2',
        font:'gray'
      },
      {
        color:'#029cd4',
        font:'white'
      },
      {
        color:'#0080b0',
        font:'white'
      },
      {
        color:'#00668e',
        font:'white'
      },
    ],
    kuoColorPurple:[
      {
        color:'#8e56dd',
        font:'white'
      },
      {
        color:'#fbf0ff',
        font:'gray'
      },
      {
        color:'#eedcff',
        font:'gray'
      },
      {
        color:'#dcbfff',
        font:'gray'
      },
      {
        color:'#c69cff',
        font:'gray'
      },
      {
        color: '#ad75fe',
        font:'white'
      },
      {
        color:'#8e56dd',
        font:'white'
      },
      {
        color:'#7137bf',
        font:'white'
      },
    ],
    kuoColorYellow:[
      {
        color:'#f5ba18',
        font:'white'
      },
      {
        color:'#fff5e4',
        font:'gray'
      },
      {
        color:'#ffe7b5',
        font:'gray'
      },
      {
        color:'#ffd36d',
        font:'gray'
      },
      {
        color:'#f5ba18',
        font:'gray'
      },
      {
        color: '#d8a100',
        font:'white'
      },
      {
        color:'#b38500',
        font:'white'
      },
      {
        color:'#8b6600',
        font:'white'
      },
    ],
    kuoColorPink:[
      {
        color:'#e851b3',
        font:'white'
      },
      {
        color:'#fff0f6',
        font:'gray'
      },
      {
        color:'#ffd8eb',
        font:'gray'
      },
      {
        color:'#ffaedc',
        font:'gray'
      },
      {
        color:'#ff79cd',
        font:'gray'
      },
      {
        color: '#e851b3',
        font:'white'
      },
      {
        color:'#c43695',
        font:'white'
      },
      {
        color:'#a12279',
        font:'white'
      },
    ],
  },

  back() {
    wx.navigateBack();
  },

  
})